version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: ${NGINX_CONTAINER_NAME:-cs2_skin_helper_nginx}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./deploy/nginx/default.conf.template:${NGINX_MOUNTING_AREA:-/etc/nginx/templates/default.conf.template}
      - ./:${APP_MOUNTING_AREA:-/var/www/cs2-skin-helper/app}
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
      APP_PUBLIC_PATH: ${APP_MOUNTING_AREA:-/var/www/cs2-skin-helper/app}/public
      APP_CONTAINER_NAME: ${APP_CONTAINER_NAME:-cs2_skin_helper_app}
      APP_PORT: ${APP_PORT:-9000}
    depends_on:
      - app
    networks:
      - ${DOCKER_NETWORK:-cs2_skin_helper}

  app:
    build:
      context: ./deploy/app
      dockerfile: Dockerfile
    container_name: ${APP_CONTAINER_NAME:-cs2_skin_helper_app}
    image: ${APP_CONTAINER_NAME:-cs2_skin_helper_app}
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "${APP_PORT:-9000}"
    volumes:
      - ./:${APP_MOUNTING_AREA:-/var/www/cs2-skin-helper/app}
      - ./deploy/app/php.ini:${APP_PHP_CONFIG_PATH:-/usr/local/etc/php/php.ini}
    depends_on:
      - db
    networks:
      - ${DOCKER_NETWORK:-cs2_skin_helper}

  db:
    container_name: ${DB_CONTAINER_NAME:-cs2_skin_helper_db}
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./deploy/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - ${DOCKER_NETWORK:-cs2_skin_helper}
networks:
  cs2_skin_helper:
    driver: bridge